GET http://localhost:80/api/category/2
Accept: application/json

###

###
POST http://localhost:4444/api/warehouse/add
Content-Type: application/json

{
  "name": "Sklad 4"
}

###
PUT http://localhost:80/api/warehouse/edit/1
Content-Type: application/json

{
}

###
POST http://localhost:80/output/add
Content-Type: application/json

{
  "date": "2020-12-01",
  "clientId": 1,
  "warehouseId": 1,
  "currencyId": 1
}


###
GET http://localhost:80/api/warehouse/changeStatus/2

###

###
DELETE http://localhost:80/api/warehouse/10

###

###
POST http://localhost:80/api/category/add
Content-Type: application/json

{
  "name": "Smartphone",
  "parentId": 1
}

###

###
GET http://localhost:80/api/category/byParentId/1

###

###
PUT http://localhost:80/api/category/edit/2
Content-Type: application/json

{
  "name": "Telefon"
}

###



###
POST http://localhost:80/api/product
Content-Type: application/json

{
  "name": "REDMI NOTE 8",
  "categoryId": 2,
  "measurementId": 1
}

###
###
GET http://localhost:80/api/product/search?name="REDMI"
###
###
GET http://localhost:80/api/product/2

###



